# Velocity Commands
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/scout/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Odometry
- ros_topic_name: "/odometry"
  gz_topic_name: "/scout/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Scout Pose TF
- ros_topic_name: "/tf"
  gz_topic_name: "/scout/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# 2D LiDAR
- ros_topic_name: "/laser_scan"
  gz_topic_name: "/scout/laser_scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# 3D LiDAR
- ros_topic_name: "/points"
  gz_topic_name: "/scout/pointcloud/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# Joint States (Gazebo world must be named "custom")
- ros_topic_name: "/scout/joint_states"
  gz_topic_name: "/world/custom/model/scout_v2/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Static TFs
- ros_topic_name: "/tf_static"
  gz_topic_name: "/scout/tf_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/imu"
  gz_topic_name: "/scout/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
